### ISSUE TITLE
UI Clarity - which tabs to follow

### ISSUE THREAD

**Issue by mptaws** [brentley/ecsworkshop#145]
Following a thread from the containers-ambassadors slack channel, the UI should clarify which tabsets to follow as you go through the workshop.   Each tabset has selections like copilot-cli, cdk, ecs-cli. etc.   Its not clear in the UI where the user should follow the diretions in all the tabs, or just pick one and stick with it through the rest of the course.  
![Screen Shot 2021-01-26 at 10 34 13 AM](https://user-images.githubusercontent.com/42448616/105888649-170db300-5fc2-11eb-8826-78eac9285e2a.png)

**Comment by adamjkeller** [comment]
hey @mptaws, this is great feedback! It definitely wouldn't hurt to have a section in the "Start the workshop" chapter explaining the paths. We love PR's and always welcome them :-) Would you be willing to give it a shot?

**Comment by mptaws** [comment]
Absolutely - I'm part of the AAoD program and am running containers ambassadors program for the startup SA group.   Any specific process to follow here ?

**Comment by mptaws** [comment]
merged
