### ISSUE TITLE
Could not find any VPCs matching error when running capacity providers install step

### ISSUE THREAD

**Issue by geremyCohen** [brentley/ecsworkshop#97]
I've gone through the workshop so far in fargate mode, and when I get to the https://ecsworkshop.com/capacity_providers/fargate/#deploy step, when I run the command, I get:

```
[Error at /ecsworkshop-capacityproviders-fargate/ecsworkshop-capacityproviders-fargate] Could not find any VPCs matching {"account":"123x","region":"us-east-1","filter":{"tag:Name":"ecsworkshop-base/BaseVPC"},"returnAsymmetricSubnets":true}
Found errors
```

I seem to have two VPCs created for ECS, but none of them are tagged "ecsworkshop-base/BaseVPC" and its not clear to me which one should be.

**Comment by adamjkeller** [comment]
Hey @geremyCohen thanks for the feedback. Did you run through the ecs-cli section prior to the capacity providers section?

There is an issue right now with the capacity provider and stateful workload sections being reliant on running through the three tier web app section using the cdk. If you use the ecs cli, it will not work. A fix for this is coming soon.

**Comment by adamjkeller** [comment]
This issue should now be resolved as each section can now be run on its own.

https://github.com/brentley/ecsworkshop/pull/101
